import type { Category, Badge } from '@/types'

export const HABIT_ICONS = [
  'Dumbbell', 'BookOpen', 'Droplets', 'Moon', 'Apple', 'Brain',
  'Heart', 'FootprintsIcon', 'Music', 'Pencil', 'Flame', 'Sun',
  'Coffee', 'Bike', 'Palette', 'Code', 'Leaf', 'Zap',
  'Star', 'Trophy', 'Target', 'Smile', 'Clock', 'TrendingUp',
  'Pilcrow', 'Ear', 'Eye', 'Hand', 'Shield', 'Wind',
]

export const HABIT_COLORS = [
  '#10B981', '#F59E0B', '#EF4444', '#3B82F6', '#8B5CF6',
  '#EC4899', '#F97316', '#14B8A6', '#6366F1', '#84CC16',
  '#06B6D4', '#D946EF', '#E11D48', '#65A30D', '#7C3AED',
  '#DB2777', '#0891B2', '#CA8A04', '#DC2626', '#4F46E5',
]

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'health', name: '健康', icon: 'Heart', color: '#EF4444' },
  { id: 'fitness', name: '运动', icon: 'Dumbbell', color: '#F97316' },
  { id: 'learning', name: '学习', icon: 'BookOpen', color: '#3B82F6' },
  { id: 'lifestyle', name: '生活', icon: 'Coffee', color: '#10B981' },
  { id: 'mindfulness', name: '冥想', icon: 'Brain', color: '#8B5CF6' },
  { id: 'creative', name: '创意', icon: 'Palette', color: '#EC4899' },
  { id: 'social', name: '社交', icon: 'Smile', color: '#14B8A6' },
  { id: 'finance', name: '理财', icon: 'TrendingUp', color: '#F59E0B' },
]

export const WEEKDAY_LABELS = ['日', '一', '二', '三', '四', '五', '六']

export const HEATMAP_LEVELS = [
  'bg-zinc-100',
  'bg-emerald-100',
  'bg-emerald-300',
  'bg-emerald-500',
  'bg-emerald-700',
  'bg-emerald-900',
]

export const BADGE_RARITY_COLORS: Record<string, { bg: string; border: string; text: string; glow: string }> = {
  bronze: { bg: '#CD7F32', border: '#8B4513', text: '#FFF8DC', glow: 'rgba(205, 127, 50, 0.4)' },
  silver: { bg: '#C0C0C0', border: '#808080', text: '#FFFFFF', glow: 'rgba(192, 192, 192, 0.4)' },
  gold: { bg: '#FFD700', border: '#B8860B', text: '#4A3000', glow: 'rgba(255, 215, 0, 0.5)' },
  platinum: { bg: '#E5E4E2', border: '#A8A9AD', text: '#2C3E50', glow: 'rgba(229, 228, 226, 0.5)' },
  legendary: { bg: 'linear-gradient(135deg, #9B59B6, #E74C3C, #F39C12)', border: '#8E44AD', text: '#FFFFFF', glow: 'rgba(155, 89, 182, 0.6)' },
}

export const BADGE_CATEGORY_NAMES: Record<string, string> = {
  streak: '连续打卡',
  milestone: '里程碑',
  social: '社交达人',
  explorer: '探索者',
  special: '特殊成就',
}

export const DEFAULT_BADGES: Badge[] = [
  {
    id: 'streak-7',
    name: '初露锋芒',
    description: '连续打卡7天',
    icon: 'Flame',
    color: '#F97316',
    category: 'streak',
    rarity: 'bronze',
    condition: { type: 'streak', target: 7 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'streak-30',
    name: '坚持不懈',
    description: '连续打卡30天',
    icon: 'Flame',
    color: '#EA580C',
    category: 'streak',
    rarity: 'silver',
    condition: { type: 'streak', target: 30 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'streak-100',
    name: '百日征程',
    description: '连续打卡100天',
    icon: 'Flame',
    color: '#DC2626',
    category: 'streak',
    rarity: 'gold',
    condition: { type: 'streak', target: 100 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'streak-365',
    name: '年度战士',
    description: '连续打卡365天',
    icon: 'Trophy',
    color: '#B91C1C',
    category: 'streak',
    rarity: 'legendary',
    condition: { type: 'streak', target: 365 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'total-10',
    name: '新手起步',
    description: '累计打卡10次',
    icon: 'Target',
    color: '#10B981',
    category: 'milestone',
    rarity: 'bronze',
    condition: { type: 'total_checkins', target: 10 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'total-100',
    name: '百次达人',
    description: '累计打卡100次',
    icon: 'Target',
    color: '#059669',
    category: 'milestone',
    rarity: 'silver',
    condition: { type: 'total_checkins', target: 100 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'total-500',
    name: '打卡狂人',
    description: '累计打卡500次',
    icon: 'Target',
    color: '#047857',
    category: 'milestone',
    rarity: 'gold',
    condition: { type: 'total_checkins', target: 500 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'total-1000',
    name: '千次传奇',
    description: '累计打卡1000次',
    icon: 'Crown',
    color: '#065F46',
    category: 'milestone',
    rarity: 'legendary',
    condition: { type: 'total_checkins', target: 1000 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'habits-3',
    name: '多面手',
    description: '创建3个习惯',
    icon: 'Star',
    color: '#8B5CF6',
    category: 'explorer',
    rarity: 'bronze',
    condition: { type: 'habit_count', target: 3 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'habits-10',
    name: '习惯大师',
    description: '创建10个习惯',
    icon: 'Star',
    color: '#7C3AED',
    category: 'explorer',
    rarity: 'silver',
    condition: { type: 'habit_count', target: 10 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'category-master',
    name: '全能选手',
    description: '在所有分类中都有打卡记录',
    icon: 'Award',
    color: '#3B82F6',
    category: 'explorer',
    rarity: 'gold',
    condition: { type: 'category_master', target: 8 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'posts-10',
    name: '分享达人',
    description: '发布10条打卡动态',
    icon: 'Send',
    color: '#EC4899',
    category: 'social',
    rarity: 'bronze',
    condition: { type: 'posts', target: 10 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'posts-50',
    name: '社交明星',
    description: '发布50条打卡动态',
    icon: 'Send',
    color: '#DB2777',
    category: 'social',
    rarity: 'silver',
    condition: { type: 'posts', target: 50 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'likes-100',
    name: '人气王',
    description: '获得100个赞',
    icon: 'Heart',
    color: '#EF4444',
    category: 'social',
    rarity: 'gold',
    condition: { type: 'likes', target: 100 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'friends-10',
    name: '交友广泛',
    description: '添加10位好友',
    icon: 'Users',
    color: '#14B8A6',
    category: 'social',
    rarity: 'silver',
    condition: { type: 'friends', target: 10 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'early-bird',
    name: '早起鸟儿',
    description: '连续7天在早上6点前打卡',
    icon: 'Sun',
    color: '#F59E0B',
    category: 'special',
    rarity: 'platinum',
    condition: { type: 'streak', target: 7 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'night-owl',
    name: '夜猫子',
    description: '连续7天在晚上10点后打卡',
    icon: 'Moon',
    color: '#6366F1',
    category: 'special',
    rarity: 'platinum',
    condition: { type: 'streak', target: 7 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'perfect-week',
    name: '完美一周',
    description: '一周内完成所有习惯的全部打卡',
    icon: 'CheckCircle',
    color: '#22C55E',
    category: 'special',
    rarity: 'gold',
    condition: { type: 'streak', target: 7 },
    createdAt: new Date().toISOString(),
  },
]

export const DEFAULT_AVATARS = [
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Aneka',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Luna',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Max',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Zoe',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Jack',
]

export const MOCK_FRIENDS = [
  { id: 'friend-1', name: '小明', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix', status: 'accepted' as const },
  { id: 'friend-2', name: '小红', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aneka', status: 'accepted' as const },
  { id: 'friend-3', name: '小华', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Luna', status: 'accepted' as const },
  { id: 'friend-4', name: '小李', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Max', status: 'pending' as const },
]

export const EXP_PER_LEVEL = 100
export const EXP_PER_CHECKIN = 10
export const EXP_PER_POST = 5
export const EXP_PER_LIKE = 2
